version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  web:
    build: .
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A celery_config:app worker --loglevel=info"
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    restart: on-failure

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    command: "celery -A celery_config:app beat --loglevel=info"
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    restart: on-failure


  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: "celery -A celery_config:app flower --address=0.0.0.0"
    depends_on:
      - celery-worker
      - celery-beat
    env_file:
      - .env
